### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/MerrittLink#3]
Would it be possible to incorporate a reporting element to Merritt Link? For instance, an Admin could generate a report of all of the items that had been exported into Merritt, the date of export, and the ark (and additional fields such as collection, or DC fields could be added to the report based on the desires of the Admin)? CSV would be ideal output format for the report.

**Comment by NedHenry** [comment]
This sounds useful, and we can definitely implement that. The plugin does already keep track of this information after the exports complete. It will take a little time to make the user interface for generating these reports (choosing date range, fields to include, etc) but otherwise it should be relatively straightforward.

**Comment by NedHenry** [comment]
I added this feature (in very simple form) to the newest version of the plugin. The new feature needs more testing and probably some interface tweaks/additions, but I'm closing this issue since we've got minimal functionality now.
